conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = true,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Fira Code SemiBold:size=15',
    gap_x = 60,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,


color1 = '007BFF',
color2 = '50FA7B',
color3 = 'ffffff',
}

	conky.text = [[
${font Symbols Nerd Font Mono:size=15}${font Fira Code SemiBold:size=20} System info${font}
${color1}•${color2}OS Name: $sysname
${color1}•${color2}Hostname: $nodename 
${color1}•${color2}Kernel: $kernel 
${color1}•${color2}Architecture: $machine
${color1}•${color2}Uptime:$color1 $uptime


${color}${font Symbols Nerd Font Mono:size=20}${font Fira Code SemiBold:size=20} Usage${font}
${color1}•${color2}RAM Usage:$color1 $mem/$memmax - $memperc% 
${color1}•${color2}CPU Usage:$color1 $cpu% 
${color1}•${color2}NVMe ${color1}${fs_used /}/${fs_size /}


${color}${font Symbols Nerd Font Mono:size=20}${font Fira Code SemiBold:size=20} Device sensors${font}
${color1}•${color2}Battery ${color1}%${battery_percent BATT} ${battery_bar 11,50 BATT} ${battery_status BATT}
${color1}•${color2}CPU  ${color1}${hwmon k10temp temp 1}
${color1}•${color2}GPU  ${color1}${hwmon amdgpu temp 1}
${color1}•${color2}NVMe ${color1}${hwmon nvme temp 1} 


]]
