[colors]
; Основные цвета, взятые из стандартной темы Greybird. При желании их можно изменить.
background = #000000
background-alt = #000000
foreground = #fff8cb
foreground-alt = #3028B0
primary = #000000
secondary = #e78a4e
alert = #cc241d
urgent = #cc241d


[bar/HDMI-0]
monitor = HDMI-0 
bottom = true
width = 90%
height = 26
offset-x = 5%
offset-y = 0
fixed-center = true

padding-right = 2

border-color = #ede6c2
border-size = 1 

; Радиус скругления углов
radius = 0

; Отступы для модулей
module-margin-left = 1
module-margin-right = 1

; Шрифты
font-0 = "Fira Code Retina:size=10;2"
font-1 = "Symbols Nerd Font Mono:size=13"

; Цвет фона панели
background = ${colors.background}
foreground = ${colors.foreground}

; Прозрачность
background-alpha = 255

; Горизонтальное выравнивание модулей: слева - рабочие столы,
; по центру - часы, справа - раскладка клавиатуры и системный трей
modules-left = xworkspaces
modules-center = date
modules-right = xkeyboard tray


cursor-click = pointer
cursor-scroll = ns-resize

override-redirect = false

[xsettings]
gtk-theme = Greybird
gtk-cursor-theme-name = WhiteSur-Dark
gtk-cursor-theme-size = 0

[global/wm]
margin-top = 0
margin-bottom = 0

[module/xworkspaces]
type = internal/xworkspaces

label-active = 󰮄
label-active-background = ${colors.background-alt}
label-active-underline = ${colors.primary}
label-active-padding = 2

label-occupied = 󰮄
label-occupied-padding = 2

label-urgent = 󰆧
label-urgent-background = ${colors.urgent}
label-urgent-padding = 2

label-empty = 󰆧
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

label-separator = |

enable-click = true
enable-scroll = true


[module/date]
type = internal/date

date = %a %d %b %Y %H:%M:%S

date-alt = %a %d %b %y %I:%M:%S %p

interval = 1.0

click-left = xfce4-calendar


[module/xkeyboard]
type = internal/xkeyboard

label-layout = %layout%
label-layout-foreground = ${colors.foreground}

label-indicator-padding = 2
label-indicator-margin = 2
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.primary}

blacklist = [ "num lock" ]

click-left = setxkbmap -next


[module/tray]
type = internal/tray

tray-size = 20

tray-transparent = true

tray-padding = 2

tray-maxsize = 16
